Feature/note create
dalbanhi/git-note pull request #9
Opened 2024-06-21 15:44 UTC by dalbanhi

### Create Note 

#### New features

- [x] implemented creation of new features
- [x] used caching to immediately refetch posts and tags
- [x] added copy/paste functionality to code blocks

See video here: [Create note testing](https://www.loom.com/share/06d6ab9c7180442db22a2646c49cc8bd?sid=921f3099-7cd8-4494-8cda-7147e847718f)

#### Known bugs

- [ ] Markdown editor cursor is sometimes off from actual writing
- [ ] copy/paste addition on multi-line code block is missing/inconsistent

2024-06-21 17:06 UTC, brandonetter requested changes
I wanted to just give you a quicker reply in regards to the errors you were having.

I'll continue checking this but for now the form feels great.

2024-06-21 17:06 UTC, brandonetter commented on src/components/shared/Form/Post/CreatePostForm.tsx
> +      <PostSpecial type={watchType} />
The issue with your image upload is coming from here.

The issue is that it's re-rendering whenever the entire `CreatePostForm` state changes. This is because it's a function being declared INSIDE of `CreatePostForm`, so when the state changes it recreates this function.

To fix this you have a couple options:

### 1) Create This Component outside of `CreatePostForm`:
```js
const PostSpecial = ({
  type,
  control,
  register,
  setSubmitButtonDisabled,
}: any) => {
  switch (type) {
    case "component":
      return (
        <CodeEditor
          key="codeEditor"
          control={control}
          setSubmitButtonDisabled={setSubmitButtonDisabled}
        />
      );
    case "workflow":
      return (
        <DynamicChecklist
          register={register}
          control={control}
          fieldStringLabel="Steps to follow"
          fieldArrayName="stepsToFollow"
          placeholderText="Enter a step to follow"
        />
      );
    case "knowledge":
      return (
        <DynamicChecklist
          register={register}
          control={control}
          fieldStringLabel="What you learned"
          fieldArrayName="whatYouLearned"
          placeholderText="Enter what you learned"
        />
      );
    default:
      return null;
  }
};

const CreatePostForm: React.FC<CreatePostFormProps> = ({ tagsString }) => {
...
return (
...
      <PostSpecial
        control={control}
        register={register}
        setSubmitButtonDisabled={setSubmitButtonDisabled}
        type={watchType}
      />
  ...
  );
}
```

This means we have to pass in the control/register and other function to it- but it won't be rerendered.

### 2) Conditionally render the components instead of this function

```js
const CreatePostForm: React.FC<CreatePostFormProps> = ({ tagsString }) => {
...
return (
...
      {watchType === "component" && (
          <CodeEditor
          key="codeEditor"
          control={control}
          setSubmitButtonDisabled={setSubmitButtonDisabled}
        />
      )}
      {watchType === "workflow" && (
          <DynamicChecklist
          register={register}
          control={control}
          fieldStringLabel="Steps to follow"
          fieldArrayName="stepsToFollow"
          placeholderText="Enter a step to follow"
        /> 
      )}
      {watchType === "knowledge" && (
          <DynamicChecklist
          register={register}
          control={control}
          fieldStringLabel="What you learned"
          fieldArrayName="whatYouLearned"
          placeholderText="Enter what you learned"
        />
      )}
      ...
      )
 }
 ```
 
 Either solution will fix the rerender.
 

https://github.com/dalbanhi/git-note/assets/4108484/c4a82a94-f685-4ad8-88db-5d3fbc200e6c

2024-06-21 17:06 UTC, brandonetter commented on src/components/shared/Form/Post/CodeEditor/CodeEditor.tsx
I am unable to recreate the issue with the codeeditor's cursor being mispositioned. 

Likely this is a style issue- I would say open up the inspector next time this happens, and see if you can disable/enable certain text related styles on the editor/editor's parent until one fixes it. Then you can apply a style to override and prevent that from happening. 

Maybe we can discuss this in the meeting.

In the meantime I will continue trying to recreate the bug so I can provide some better feedback. Does this ever happen in chrome?

2024-06-21 18:02 UTC, brandonetter requested changes
Looks amazing! Great work.

2024-06-21 18:02 UTC, brandonetter commented on src/components/shared/Form/Post/CodeEditor/ImagePreviewUploader.tsx
> +            if (ready)
I'm guessing this was left from testing!

2024-06-21 18:02 UTC, brandonetter commented on src/components/shared/Form/Post/MarkdownEditPreview/MarkdownEditPreview.tsx
> +              // ref,
```suggestion
```

2024-06-21 18:02 UTC, brandonetter commented on src/components/shared/Form/Post/MarkdownEditPreview/MarkdownEditPreview.css
The editor looks fantastic. So good work all around here. If there's anything you want to add to the styling or change anything let me know- but you've done an excellent job here!

2024-06-21 18:02 UTC, brandonetter commented on src/components/shared/Form/Post/MarkdownEditPreview/MarkdownEditPreview.tsx
> +              onBlur,
We can remove that blue border by applying classes to remove any focus rings to the textarea itself:

```suggestion
  textareaProps={{
              placeholder: "Please enter Markdown text",
              onBlur,
              className:
                "border-transparent focus:border-transparent focus:ring-0 ",
```

2024-06-21 18:02 UTC, brandonetter commented on src/components/shared/Post/RenderMarkdown.tsx
For this- what you're really doing is rendering a `custom` component instead of a regular 'pre' tag.

You're creating a new instance of react to render into it- which is a really cool idea. And I've suggested this kind of technique for when we don't have access to the underlying element (like from a third party application).

In this case however, we can tell the Markdown renderer to use our own custom code to replace other tags!

```js

  return (
    <Markdown
      components={{
        pre(props) {
          const { children, ...rest } = props;
            return (
              <pre {...rest} >
                {children}
              </pre>
          );
        },
      }}
    >
      {content}
    </Markdown>
  );
```

All we need to do is pass in a 'components' property and in the example above you can see I've now taken over the "pre" tag, and now I'm rendering my own (unchanged!) version of the pre tag. We can do whatever we want here. For example if we wanted to add some text to the end of every pre tag:

```js
  pre(props) {
          const { children, ...rest } = props;
            return (
              <pre {...rest} >
                {children} SOME TEXT // <--- added 
              </pre>
          );
        },
```        

In this case, you'd like to render some clickable copy/paste button around every pre tag.

Check out the docs here: https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use-custom-components-syntax-highlight

And see if we can simplify this approach.

I would suggest something like this- though I haven't quite fully nailed your style!

```js
const CopyIcon = () => (
  <Image
    src="/icons/copy.svg"
    alt="Copy code"
    width={20}
    height={20}
    className="my-0 cursor-pointer rounded-md"
    onClick={handleCopyClick}
  />
);
export default function RenderMarkdown({ content }: any) {
  useEffect(() => {
    Prism.highlightAll();
  }, []);

  return (
    <Markdown
      components={{
        pre(props) {
          const { children, className, node, ...rest } = props;
          return (
            <pre
              {...rest}
              className={className + "flex justify-between relative"}
            >
              {children}
              <div className="absolute right-1 top-1 size-5">
                <CopyIcon />
              </div>
            </pre>
          );
        },
      }}
    >
      {content}
    </Markdown>
  );
}
```

See if we can take a cleaner approach to this and let me know if there are any issues :)

2024-06-22 19:22 UTC, dalbanhi commented
Hi Brandon, I addressed the feedback you left. Thanks again!

2024-06-24 13:03 UTC, merged